name: Check
on:
  pull_request:
  push:
    branches: [main]
permissions:
  contents: read
jobs:
  workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://rhysd/actionlint:1.7.12
  check:
    strategy:
      matrix:
        node: [24, 26]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm ci
      - run: npm run check
        env:
          ASTRO_TELEMETRY_DISABLED: '1'
